export const sliderData = [
  {
    title: "또와쑤깡",
    img: "./img/box/project_1.png",
    url: "./project1.html",
    members: ["김보미", "임희원"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "키키푸",
    img: "./img/box/project_2.png",
    url: "./project2.html",
    members: ["서동현", "오우진", "권용우"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "모글모글 어드벤처",
    img: "./img/box/project_3.png",
    url: "./project3.html",
    members: ["유은비", "김현지", "곽초은"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "마법의 샌드위치",
    img: "./img/box/project_4.png",
    url: "/project4.html",
    members: ["김민정", "김선정", "노채린"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "독도탐사대",
    img: "./img/box/project_5.png",
    url: "/project5.html",
    members: ["강유림"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "저승길의 동반자 꼭두",
    img: "./img/box/project_6.png",
    url: "/project6.html",
    members: ["조서영", "최희선", "이현서"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "벽사야담",
    img: "./img/box/project_7.png",
    url: "/project7.html",
    members: ["김도희", "정예원", "반상우"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "두들박스",
    img: "./img/box/project_8.png",
    url: "/project8.html",
    members: ["민유진", "박미소"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "패럴림픽",
    img: "./img/box/project_9.png",
    url: "/project9.html",
    members: ["조예리", "정유민"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "백구",
    img: "./img/box/project_10.png",
    url: "/project10.html",
    members: ["이새연", "이채현", "박기연"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_11.png",
    url: "/project11.html",
    members: ["조범규", "윤정원"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_12.png",
    url: "/project12.html",
    members: ["이연우", "손예진"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_13.png",
    url: "/project13.html",
    members: ["김지수", "김윤주"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_14.png",
    url: "/project14.html",
    members: ["황지원", "황서진", "고현희"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_15.png",
    url: "/project15.html",
    members: ["박서희", "백진주", "이채민"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_16.png",
    url: "/project16.html",
    members: ["오효진", "나원호"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_17.png",
    url: "/project17.html",
    members: ["이주연"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_18.png",
    url: "/project18.html",
    members: ["왕뢰이저"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_19.png",
    url: "/project19.html",
    members: ["양윤보", "박지수"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_20.png",
    url: "/project20.html",
    members: ["박순후", "김루나"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_21.png",
    url: "/project21.html",
    members: ["이소현"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
  {
    title: "똑똑",
    img: "./img/box/project_22.png",
    url: "/project22.html",
    members: ["김현진", "최서윤"],
    description: "디지털 정보의 사후처리\n잘 남기는 것에 대한 고민",
    subjects: ["인터랙션디자인", "서비스경험디자인"],
  },
];
